apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy-svc
  labels:
    app: nginx-svc
    type: deploy-proxy

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30100
  selector:
    app: nginx
    type: proxy