apiVersion: v1
kind: PersistentVolumeClaim
metadata:                 
  name: postgres-pv-claim
  labels:
    app: demo-app
spec:                     
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi